allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  core-js: false
  esbuild: true
  prisma: true
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  braces@<3.0.3: '>=3.0.3'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
