org: rems8
app: ozari
service: ozari-api

stages:
  prod:
    observability: true
    params:
      AWS_REGION: us-east-1
      NODE_VERSION: nodejs22.x
      NODE_TARGET: node22
      LOG_FORMAT: JSON
      LOG_LEVEL: INFO
      API_BASE_PATH: /api
      THROTTLING_BURST: 200
      THROTTLING_RATE: 100
  default:
    observability: false
    params:
      AWS_REGION: us-east-1
      NODE_VERSION: nodejs22.x
      NODE_TARGET: node22
      LOG_FORMAT: JSON
      LOG_LEVEL: INFO
      API_BASE_PATH: /api
      THROTTLING_BURST: 50
      THROTTLING_RATE: 20

provider:
  name: aws
  runtime: ${param:NODE_VERSION}
  region: ${param:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  architecture: arm64
  memorySize: 1024
  timeout: 15
  logRetentionInDays: 30
  logs:
    httpApi: true
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - 'arn:aws:ssm:${self:provider.region}:*:parameter/ozari/${self:provider.stage}/*'
  vpc:
    securityGroupIds:
      - ${ssm:/ozari/${self:provider.stage}/lambda_sg_id}
    subnetIds:
      - ${ssm:/ozari/${self:provider.stage}/lambda_subnet_1}
      - ${ssm:/ozari/${self:provider.stage}/lambda_subnet_2}
  environment:
    API_ENV: ${env:API_ENV, 'dev'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    APP_HOST: ${ssm:/ozari/${self:provider.stage}/app_host}
    DATABASE_URL: ${env:DATABASE_URL, ssm:/ozari/${self:provider.stage}/database_url}
  tags:
    project: ozari-api
    stage: ${sls:stage}

plugins:
  - serverless-offline

package:
  patterns:
    - src/locales/**
    - '!src/**/*.test.ts'
    - '!README.md'

resources:
  Resources:
    HttpApiStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        DefaultRouteSettings:
          ThrottlingBurstLimit: ${param:THROTTLING_BURST}
          ThrottlingRateLimit: ${param:THROTTLING_RATE}

functions:
  health:
    handler: src/modules/health/health.handler
    #reservedConcurrency: 2
    events:
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/health
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/health/{proxy+}
  auth:
    handler: src/modules/auth/auth.handler
    #reservedConcurrency: 5
    events:
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/auth
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/auth/{proxy+}
  products:
    handler: src/modules/products/products.handler
    #reservedConcurrency: 5
    events:
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/products
      - httpApi:
          method: ANY
          path: ${param:API_BASE_PATH}/products/{proxy+}
