/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SesionRouteImport } from './routes/sesion'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SesionInicioRouteImport } from './routes/sesion/inicio'
import { Route as SesionSplatRouteImport } from './routes/sesion/$'

const SesionRoute = SesionRouteImport.update({
  id: '/sesion',
  path: '/sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SesionInicioRoute = SesionInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => SesionRoute,
} as any)
const SesionSplatRoute = SesionSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SesionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  id: '__root__' | '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SesionRoute: typeof SesionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sesion': {
      id: '/sesion'
      path: '/sesion'
      fullPath: '/sesion'
      preLoaderRoute: typeof SesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesion/inicio': {
      id: '/sesion/inicio'
      path: '/inicio'
      fullPath: '/sesion/inicio'
      preLoaderRoute: typeof SesionInicioRouteImport
      parentRoute: typeof SesionRoute
    }
    '/sesion/$': {
      id: '/sesion/$'
      path: '/$'
      fullPath: '/sesion/$'
      preLoaderRoute: typeof SesionSplatRouteImport
      parentRoute: typeof SesionRoute
    }
  }
}

interface SesionRouteChildren {
  SesionSplatRoute: typeof SesionSplatRoute
  SesionInicioRoute: typeof SesionInicioRoute
}

const SesionRouteChildren: SesionRouteChildren = {
  SesionSplatRoute: SesionSplatRoute,
  SesionInicioRoute: SesionInicioRoute,
}

const SesionRouteWithChildren =
  SesionRoute._addFileChildren(SesionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SesionRoute: SesionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
