/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SesionImport } from './routes/sesion'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as SesionInicioImport } from './routes/sesion/inicio'
import { Route as SesionSplatImport } from './routes/sesion/$'

// Create/Update Routes

const SesionRoute = SesionImport.update({
  id: '/sesion',
  path: '/sesion',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SesionInicioRoute = SesionInicioImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => SesionRoute,
} as any)

const SesionSplatRoute = SesionSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SesionRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/sesion': {
      id: '/sesion'
      path: '/sesion'
      fullPath: '/sesion'
      preLoaderRoute: typeof SesionImport
      parentRoute: typeof rootRoute
    }
    '/sesion/$': {
      id: '/sesion/$'
      path: '/$'
      fullPath: '/sesion/$'
      preLoaderRoute: typeof SesionSplatImport
      parentRoute: typeof SesionImport
    }
    '/sesion/inicio': {
      id: '/sesion/inicio'
      path: '/inicio'
      fullPath: '/sesion/inicio'
      preLoaderRoute: typeof SesionInicioImport
      parentRoute: typeof SesionImport
    }
  }
}

// Create and export the route tree

interface SesionRouteChildren {
  SesionSplatRoute: typeof SesionSplatRoute
  SesionInicioRoute: typeof SesionInicioRoute
}

const SesionRouteChildren: SesionRouteChildren = {
  SesionSplatRoute: SesionSplatRoute,
  SesionInicioRoute: SesionInicioRoute,
}

const SesionRouteWithChildren =
  SesionRoute._addFileChildren(SesionRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sesion': typeof SesionRouteWithChildren
  '/sesion/$': typeof SesionSplatRoute
  '/sesion/inicio': typeof SesionInicioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  id: '__root__' | '/' | '/$' | '/sesion' | '/sesion/$' | '/sesion/inicio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SesionRoute: typeof SesionRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SesionRoute: SesionRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/sesion"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/sesion": {
      "filePath": "sesion.tsx",
      "children": [
        "/sesion/$",
        "/sesion/inicio"
      ]
    },
    "/sesion/$": {
      "filePath": "sesion/$.tsx",
      "parent": "/sesion"
    },
    "/sesion/inicio": {
      "filePath": "sesion/inicio.tsx",
      "parent": "/sesion"
    }
  }
}
ROUTE_MANIFEST_END */
